# Docker Compose configuration for setting up a Docking Station container
#
# This service will be used to monitor and upgrade our docker containers
services:
  # Docking Station Container
  docking-station:
    image: loolzzz/docking-station:latest                                 # Pull the latest version of the docking-station image
    container_name: docking-station                                       # Name of the docking-station container
    hostname: ${HOST:?Please supply FQDN for the container}               # Hostname for the docking-station container
    
    restart: unless-stopped                                               # Restart the container unless manually stopped

    # Ports forwarded to host from container
    ports:
      - 3000:3000                                                         # Application port

    volumes:
      - /srv/docking-station/config:/config
      - /srv/docking-station/data:/data
      - /srv/docking-station/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      # you should add mount points for each containers' docker-compose file you intend on update using this tool
      # i usually put everything in a single neat folder under
      #  ⚠️ left stacks path == right stacks path (MUST)
      - ../:/mnt/compose-files

    # docking-station tracking
    labels:
      - 'com.loolzzz.docking-station.enabled=true'