# Docker Compose configuration for setting up PiHole container
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  # PiHole container
  pihole:
    image: pihole/pihole:latest                         # Pull latest build of pihole image
    container_name: pihole                              # Name of the container
    hostname: ${HOSTNAME:?fqdn for container}           # Hostname of the container

    restart: unless-stopped                             # Restart the container unless manually stopped
    
    ports:
      - "53:53/tcp"                                     # DNS Ports
      - "53:53/udp"                                     # DNS Ports
      - "80:80/tcp"                                     # Default HTTP Port
      - "443:443/tcp"                                   # Default HTTPs Port.
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    
    # Environment variables associated with PiHole 
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Asia/Kolkata'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '${WEBSERVER_PASSWORD:?set password for web login}'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/etc/pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'

    # Container labels for additional metadata
    labels:
      - "com.centurylinklabs.watchtower.enable=true"                      # Enable automatic updates with Watchtower

    # Deployment (docker compose up) settings
    deploy:
      # Set resource limits
      resources:
        # maximum resource limits
        limits:
          cpus: '0.5'
          memory: 1024m
        # minimum resource limits
        reservations:
          cpus: '0.1'
          memory: 32m