# Docker Compose configuration for setting up PiHole container
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  # PiHole container
  pihole:
    # container image
    image: pihole/pihole:latest
    # container name
    container_name: pihole
    # container host
    hostname: pihole-service

    # restart the container unless manually stopped
    restart: unless-stopped
    
    # ports to forward from host to container
    ports:
      # DNS Ports
      - "8053:53/tcp"
      - "8053:53/udp"
      # HTTP Port
      - "8000:80/tcp"
      # HTTPs Port
      - "8443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "8067:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "8123:123/udp"
    
    # environment variables for container
    environment:
      # set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Asia/Kolkata'
      # set a password to access the web interface. 
      # setting it to blank disables password
      FTLCONF_webserver_api_password: '${NO_PASSWORD}'
      # if using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    
    # volume mapping from host to container
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '/srv/pihole/etc:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'

    # container labels
    labels:
      - 'admins.chekuri.org=true'

    # container health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 45s
      start_interval: 40s

    # deployment (docker compose up) settings
    deploy:
      # set resource limits
      resources:
        # maximum resource limits
        limits:
          cpus: '0.1'
          memory: 1024m
        # minimum resource limits
        reservations:
          cpus: '0.05'
          memory: 32m

  # oauth2-proxy container
  oauth2-proxy:
    # container image
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    # container name
    container_name: pihole-oidc
    # container hostname
    hostname: ${HOST}
    
    # restart the container unless manually stopped
    restart: unless-stopped
    
    # command to run on container start
    command: --config /oauth2-proxy.cfg
    
    # volume mapping from host to container
    volumes:
      # oauth application configuration
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    
    # ports to be forwarded from host to container
    ports:
      # forwarding oauth2-proxy port to host
      - 8000:4180

    # container labels
    labels:
      - 'admins.chekuri.org=true'

    # container dependencies
    depends_on:
      # depends on pihole container
      pihole:
        # container must be healthy
        condition: service_healthy
    
    # deployment (docker compose up) settings
    deploy:
      # set resource limits
      resources:
        # maximum resource limits
        limits:
          cpus: '0.05'
          memory: 128m
        # minimum resource limits
        reservations:
          cpus: '0.01'
          memory: 32m